apiVersion: v1
kind: Service
metadata:
  name: my-django-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    name: web
    targetPort: 8000
    nodePort: 30180
  selector:
    app: my-django

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django
  template:
    metadata:
      labels:
        app: my-django
    spec:
      priorityClassName: low
      containers:
      - name: my-django
        image: msisdev/my-django:0.0.3
        ports:
        - containerPort: 8000
          name: web
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "1"
            memory: "256Mi"
      
