apiVersion: v1
kind: Service
metadata:
  name: my-django-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    name: web
    targetPort: 8000
    nodePort: 30180
  selector:
    app: my-django

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django
  template:
    metadata:
      labels:
        app: my-django
    spec:
      containers:
      - name: my-django
        image: msisdev/my-django:0.0.3
        ports:
        - containerPort: 8000
          name: web
        env:
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /about # Or your application's health check endpoint
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /about # Or your application's health check endpoint
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /about # Or your application's health check endpoint
            port: 8000
          failureThreshold: 30
          periodSeconds: 5
